#!/bin/sh

if ! [ -x "$(command -v brew)" ];
then
    echo "Doing android setup"
    curl -O https://download.clojure.org/install/linux-install-1.11.1.1149.sh
    chmod +x linux-install-1.11.1.1149.sh
    sudo ./linux-install-1.11.1.1149.sh
    exit
else
    echo "Doing ios setup"
    brew install clojure
    exit
fi
